target_fps: 18 # FPS otimizado para múltiplas câmeras (não use 30!)
protocol: amqp # amqp | mqtt

amqp:
  amqp_url: "amqp://user:password@rabbitmq:5672/guard_vhost"  # CORRIGIDO: vhost adicionado
  exchange: "carnes_nobres_exchange"
  routing_key_prefix: "camera."

# Compressão: Reduz banda em ~60% (IMPORTANTE para produção)
compression:
  enabled: true
  level: 3

mqtt:
  broker: "tcp://localhost:1883"
  topic_prefix: "camera/"


cameras:
  - id: "cam1"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=1&subtype=0"
  - id: "cam2"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=2&subtype=0"
  - id: "cam3"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=3&subtype=0"
  - id: "cam4"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=4&subtype=0"
  - id: "cam5"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=5&subtype=0"
  - id: "cam6"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=6&subtype=0"
  - id: "cam7"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=7&subtype=0"
  - id: "cam8"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=8&subtype=0"
  - id: "cam9"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=9&subtype=0"
  - id: "cam10"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=10&subtype=0"
  - id: "cam11"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=11&subtype=0"
  - id: "cam12"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=12&subtype=0"
  - id: "cam13"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=13&subtype=0"
  - id: "cam14"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=14&subtype=0"
  - id: "cam15"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=15&subtype=0"
  - id: "cam16"
    url: "rtsp://admin:Btk89222@@192.168.10.18:554/cam/realmonitor?channel=16&subtype=0"
  - id: "cam17"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=1&subtype=0"
  - id: "cam18"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=2&subtype=0"
  - id: "cam19"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=3&subtype=0"
  - id: "cam20"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=4&subtype=0"
  - id: "cam21"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=5&subtype=0"
  - id: "cam22"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=6&subtype=0"
  - id: "cam23"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=7&subtype=0"
  - id: "cam24"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=8&subtype=0"
  - id: "cam25"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=9&subtype=0"
  - id: "cam26"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=10&subtype=0"
  - id: "cam27"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=11&subtype=0"
  - id: "cam28"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=12&subtype=0"
  - id: "cam29"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=13&subtype=0"
  - id: "cam30"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=14&subtype=0"
  - id: "cam31"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=15&subtype=0"
  - id: "cam32"
    url: "rtsp://admin:Btk89222@@192.168.10.20:554/cam/realmonitor?channel=16&subtype=0"
  - id: "cam33"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=1&subtype=0"
  - id: "cam34"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=2&subtype=0"
  - id: "cam35"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=3&subtype=0"
  - id: "cam36"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=4&subtype=0"
  - id: "cam37"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=5&subtype=0"
  - id: "cam38"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=6&subtype=0"
  - id: "cam39"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=7&subtype=0"
  - id: "cam40"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=8&subtype=0"
  - id: "cam41"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=9&subtype=0"
  - id: "cam42"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=10&subtype=0"
  - id: "cam43"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=11&subtype=0"
  - id: "cam44"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=12&subtype=0"
  - id: "cam45"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=13&subtype=0"
  - id: "cam46"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=14&subtype=0"
  - id: "cam47"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=15&subtype=0"
  - id: "cam48"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=16&subtype=0"
  - id: "cam49"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=17&subtype=0"
  - id: "cam50"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=18&subtype=0"
  - id: "cam51"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=19&subtype=0"
  - id: "cam52"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=20&subtype=0"
  - id: "cam53"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=21&subtype=0"
  - id: "cam54"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=22&subtype=0"
  - id: "cam55"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=23&subtype=0"
  - id: "cam56"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=24&subtype=0"
  - id: "cam57"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=25&subtype=0"
  - id: "cam58"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=26&subtype=0"
  - id: "cam59"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=27&subtype=0"
  - id: "cam60"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=28&subtype=0"
  - id: "cam61"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=29&subtype=0"
  - id: "cam62"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=30&subtype=0"
  - id: "cam63"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=31&subtype=0"
  - id: "cam64"
    url: "rtsp://admin:Btk89222@@192.168.10.231:554/cam/realmonitor?channel=32&subtype=0"




redis:
  enabled: false  # DESABILITADO: Com 64 câmeras consumiria ~48GB RAM!
  address: "redis:6379"
  ttl_seconds: 300
  prefix: "frames"

metadata:
  enabled: true
  exchange: "camera.metadata"
  routing_key: "camera.metadata.event"
